/**
 * Storyboard Panel
 * Scene-by-scene storyboard with narration, visual prompt, motion style, text cues.
 * Narration = EXACT transcript. Visual/motion data generated by AI on top.
 */
import React, { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { scriptsService } from '@/services/scripts'
import { agentsService } from '@/services/agents'
import {
  Film, Sparkles, Loader2, CheckCircle, RotateCcw, ChevronDown,
  ChevronUp, AlertTriangle, Play, Lock
} from 'lucide-react'
import Button from '@/components/ui/Button'
import Spinner from '@/components/ui/Spinner'

const MOTION_STYLES = [
  'Slow Zoom In', 'Zoom Out', 'Pan Left', 'Pan Right', 'Ken Burns', 'Static'
]

export default function StoryboardPanel({ project, onUpdate }) {
  const queryClient = useQueryClient()
  const [generatingModule, setGeneratingModule] = useState(null)
  const [generatingAll, setGeneratingAll] = useState(false)
  const [error, setError] = useState(null)
  const [expandedModules, setExpandedModules] = useState({})

  const { data: scripts = [], isLoading } = useQuery({
    queryKey: ['scripts', project?.id],
    queryFn: () => scriptsService.listByProject(project.id),
    enabled: !!project?.id,
  })

  const allApproved = scripts.length > 0 && scripts.every(s => s.status === 'approved')

  const handleGenerateModule = async (moduleId) => {
    setGeneratingModule(moduleId)
    setError(null)
    try {
      await agentsService.runStoryboard(null, moduleId)
      queryClient.invalidateQueries({ queryKey: ['scenes'] })
      queryClient.invalidateQueries({ queryKey: ['scenes', moduleId] })
      onUpdate?.()
    } catch (e) {
      setError(e.message || 'Storyboard generation failed')
    } finally {
      setGeneratingModule(null)
    }
  }

  const handleGenerateAll = async () => {
    setGeneratingAll(true)
    setError(null)
    try {
      await agentsService.runStoryboard(project.id, null)
      queryClient.invalidateQueries({ queryKey: ['scenes'] })
      onUpdate?.()
    } catch (e) {
      setError(e.message || 'Storyboard generation failed')
    } finally {
      setGeneratingAll(false)
    }
  }

  if (isLoading) return <div className="flex justify-center p-16"><Spinner /></div>

  if (!allApproved) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-12 text-center">
        <Lock className="w-10 h-10 text-slate-700 mb-3" />
        <p className="text-white font-medium mb-1">Storyboard is locked</p>
        <p className="text-slate-500 text-sm">Approve all scripts first to unlock the storyboard.</p>
      </div>
    )
  }

  return (
    <div className="h-full flex flex-col">
      {/* Header */}
      <div className="px-6 py-4 border-b border-white/[0.06] flex items-center justify-between flex-shrink-0">
        <div>
          <h2 className="text-base font-semibold text-white flex items-center gap-2">
            <Film className="w-4 h-4 text-indigo-400" /> Storyboard
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            AI generates visual prompts, motion styles, and text cues from your exact narration.
          </p>
        </div>
        <Button onClick={handleGenerateAll} disabled={generatingAll} variant="primary" size="sm">
          {generatingAll
            ? <><Loader2 className="w-3.5 h-3.5 animate-spin" />Generating all…</>
            : <><Sparkles className="w-3.5 h-3.5" />Generate All Storyboards</>}
        </Button>
      </div>

      {error && (
        <div className="mx-6 mt-3 flex items-center gap-2 p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-red-300 text-xs">
          <AlertTriangle className="w-4 h-4 flex-shrink-0" />{error}
        </div>
      )}

      {/* Modules */}
      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-6">
        {scripts.map((script, vi) => (
          <ModuleStoryboard
            key={script.id}
            script={script}
            videoIndex={vi}
            isGenerating={generatingModule === script.moduleId}
            onGenerate={() => handleGenerateModule(script.moduleId)}
            expanded={expandedModules[script.id] !== false}
            onToggle={() => setExpandedModules(e => ({ ...e, [script.id]: !e[script.id] !== false }))}
          />
        ))}
      </div>
    </div>
  )
}

// ─── Module storyboard section ────────────────────────────────────────────────

function ModuleStoryboard({ script, videoIndex, isGenerating, onGenerate, expanded, onToggle }) {
  const queryClient = useQueryClient()

  const { data: scenes = [], isLoading } = useQuery({
    queryKey: ['scenes', script.moduleId],
    queryFn: () => script.moduleId
      ? fetch('/api/modules/' + script.moduleId + '/scenes').then(r => r.json())
      : Promise.resolve([]),
    enabled: !!script.moduleId,
  })

  const hasStoryboard = scenes.some(s => s.textCues || s.visualPrompt)

  return (
    <div className="rounded-2xl border border-white/[0.06] overflow-hidden">
      {/* Module header */}
      <div className="flex items-center justify-between px-4 py-3 bg-slate-900/60 border-b border-white/[0.04]">
        <button onClick={onToggle} className="flex items-center gap-3 flex-1 text-left">
          <div className="w-7 h-7 rounded-lg bg-indigo-500/20 flex items-center justify-center flex-shrink-0">
            <span className="text-xs font-bold text-indigo-400">{videoIndex + 1}</span>
          </div>
          <div>
            <p className="text-sm font-semibold text-white">{script.title}</p>
            <p className="text-xs text-slate-500">{scenes.length} scenes · {script.estimatedDurationMinutes} min</p>
          </div>
          {expanded ? <ChevronUp className="w-4 h-4 text-slate-500 ml-2" /> : <ChevronDown className="w-4 h-4 text-slate-500 ml-2" />}
        </button>
        <div className="flex items-center gap-2">
          {hasStoryboard && <span className="text-[10px] text-emerald-400 flex items-center gap-1"><CheckCircle className="w-3 h-3" />Generated</span>}
          <button
            onClick={onGenerate}
            disabled={isGenerating}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors bg-indigo-600/20 hover:bg-indigo-600/30 text-indigo-400 border border-indigo-500/20 disabled:opacity-50"
          >
            {isGenerating ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : hasStoryboard ? <RotateCcw className="w-3.5 h-3.5" /> : <Sparkles className="w-3.5 h-3.5" />}
            {isGenerating ? 'Generating…' : hasStoryboard ? 'Regenerate' : 'Build Scenes'}
          </button>
        </div>
      </div>

      {/* Scene cards */}
      {expanded && (
        isLoading ? (
          <div className="flex justify-center py-8"><Spinner size="sm" /></div>
        ) : scenes.length === 0 ? (
          <div className="py-8 text-center text-slate-600 text-sm">No scenes yet</div>
        ) : (
          <div className="p-4 grid grid-cols-1 lg:grid-cols-2 gap-4">
            {scenes.map((scene, i) => (
              <SceneCard key={scene.id} scene={scene} index={i} onUpdate={() => queryClient.invalidateQueries({ queryKey: ['scenes', script.moduleId] })} />
            ))}
          </div>
        )
      )}
    </div>
  )
}

// ─── Scene storyboard card ────────────────────────────────────────────────────

function SceneCard({ scene, index, onUpdate }) {
  const [motionStyle, setMotionStyle] = useState(
    scene.textAnimationType
      ? scene.textAnimationType.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ')
      : 'Static'
  )
  const [saving, setSaving] = useState(false)

  const textCues = (() => { try { return JSON.parse(scene.textCues || '[]') } catch { return [] } })()

  const handleMotionChange = async (style) => {
    setMotionStyle(style)
    setSaving(true)
    try {
      await fetch('/api/scenes/' + scene.id, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text_animation_type: style.toLowerCase().replace(/\s+/g, '-') }),
      })
      onUpdate?.()
    } catch {}
    finally { setSaving(false) }
  }

  const hasVisual = !!scene.visualAssetUrl

  return (
    <div className="rounded-xl bg-slate-900/60 border border-white/[0.06] overflow-hidden">
      {/* Visual preview */}
      <div className="relative w-full" style={{ paddingBottom: '56.25%' }}>
        {hasVisual ? (
          <img src={scene.visualAssetUrl} alt="" className="absolute inset-0 w-full h-full object-cover" />
        ) : (
          <div className="absolute inset-0 flex flex-col items-center justify-center bg-[#0D0F1E]">
            {scene.visualPrompt ? (
              <p className="text-xs text-slate-600 px-4 text-center leading-relaxed italic">
                {scene.visualPrompt?.slice(0, 100)}
              </p>
            ) : (
              <Film className="w-6 h-6 text-slate-700" />
            )}
          </div>
        )}
        {/* Scene badge */}
        <div className="absolute bottom-2 left-2 px-2 py-0.5 rounded-full bg-black/60 text-[10px] text-white font-bold">
          Scene {index + 1}
        </div>
        {/* Audio indicator */}
        {scene.ttsAudioUrl && (
          <div className="absolute bottom-2 right-2 px-2 py-0.5 rounded-full bg-emerald-500/20 border border-emerald-500/30 text-[10px] text-emerald-400 flex items-center gap-1">
            <Play className="w-2.5 h-2.5" /> Audio
          </div>
        )}
      </div>

      {/* Narration text — EXACT, never rewritten */}
      {scene.scriptContent && (
        <div className="px-3 pt-3 pb-1">
          <p className="text-[10px] text-slate-600 uppercase tracking-widest mb-1 font-medium">NARRATION</p>
          <p className="text-xs text-slate-300 leading-relaxed line-clamp-3">{scene.scriptContent}</p>
        </div>
      )}

      {/* Motion style */}
      <div className="px-3 pt-2 pb-1">
        <p className="text-[10px] text-slate-600 uppercase tracking-widest mb-1.5 font-medium">MOTION STYLE</p>
        <div className="grid grid-cols-3 gap-1">
          {MOTION_STYLES.map(style => (
            <button
              key={style}
              onClick={() => handleMotionChange(style)}
              disabled={saving}
              className={`px-1.5 py-1 rounded-md text-[10px] font-medium transition-all border ${
                motionStyle === style
                  ? 'bg-indigo-600/30 border-indigo-500/50 text-indigo-300'
                  : 'bg-slate-800/60 border-white/[0.04] text-slate-500 hover:border-white/15 hover:text-slate-400'
              }`}
            >
              {style}
            </button>
          ))}
        </div>
      </div>

      {/* Text cues */}
      {textCues.length > 0 && (
        <div className="px-3 pt-1 pb-2">
          <p className="text-[10px] text-slate-600 uppercase tracking-widest mb-1 font-medium">TEXT CUES</p>
          <div className="flex flex-wrap gap-1">
            {textCues.map((cue, i) => (
              <span key={i} className="px-2 py-0.5 rounded-md bg-slate-800 border border-white/[0.06] text-[10px] text-slate-400">
                {cue.text} <span className="text-slate-600">{cue.duration_seconds}s</span>
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Visual prompt */}
      {scene.visualPrompt && (
        <div className="px-3 pb-3">
          <p className="text-[10px] text-slate-600 uppercase tracking-widest mb-1 font-medium">VISUAL PROMPT</p>
          <p className="text-[10px] text-slate-500 leading-relaxed">{scene.visualPrompt}</p>
        </div>
      )}
    </div>
  )
}
